#!/usr/bin/env bash
#
# Usage: honest-pip pip:<package> <destination> [-v <version>]
#        honest-pip pip:requests /tmp/pip -v 39.0.1

# Compatibility to MAC
[[ "$OSTYPE" == "darwin"* ]] && readlink() { echo $(cd $(dirname "$2") && pwd)/$(basename "$2"); }

SCRIPT_DIR="$(readlink -f "$(dirname "$0")")"
# Import common functions and variables of honest
source "$SCRIPT_DIR"/../share/honest/common.sh

extract() {
  set -e
  # TODO(david942j): check all probably file format,
  #                  currently known: .whl(zip), .tar.gz
  set +e
}

main() {
  # Parse arguments
  while [[ "$1" != "" ]]; do
    case "$1" in
      -h|--help )
        usage
        exit 0
        ;;
      --version)
        version
        exit 0
        ;;
      -v)
        package_ver="$2"
        shift 2
        ;;
      * )
        # Exit on argument starting with hyphen "-"
        [[ "$1" == "-"* ]] && die "Unknown argument $1"
        # Remember the string type arguments in the array
        args+=("$1")
        shift
        ;;
    esac
  done

  # Check # of input arguments after parsing the input arguments
  [[ ${#args[@]} == 0 ]] && usage && exit 0
  [[ ${#args[@]} < 2 ]] && die "Both <project> and <destination> are required!"
  ! command_exist "pip" && die "Command 'pip' is not installed on your system"

  # Check the format and exit on any failure
  check_package_format "${args[0]}"

  local package="${args[0]#*:}"
  local path="${args[1]}"
  local target="$package"
  [[ "$package_ver" != "" ]] && target+="==$package_ver"

  # Download package in the temp directory
  local mesg=$(pip download --no-deps -d "$path" "$target" 2>&1)
  [[ "$mesg" != *"Successfully downloaded "* ]] && die "$mesg"

  # Get the filename.
  local name=$(echo -e "$mesg" | sed -n -e 's/^.*Saved //p')

  # Go to temp directory and extract the file
  (cd "$path" && extract "$name")
}

main "$@"

