#!/usr/bin/env bash
#
# Usage: honest [-h/--help] [-V/--version]
#               <git-url>
#               <package> [-v=]
# Examples:
#        honest --version
#        honest github:david942j/one_gadget gem:one_gadget
#        honest https://github.com/pypa/setuptools@v39.0.1 pip:setuptools -v 39.0.1
#        honest ~/path_on_my_laptop/seccomp-tools gem:seccomp-tools -v 1.2.0
#
# Options:
#        -h, --help
#               Show this usage.
#        -V, --version
#               Display version information and exit.
#
# Git Url Parameter:
#        <git-url> can be:
#               - A relative/absolute path.
#               - https://<git org>/<author>/<project>[@<branch|commit|tag>]
#               - <github|bitbucket|gitlab>:<author>/<project>[@<branch|commit|tag>]
#        If no branch/commit/tag is specified, the latest release(tag) will be used.
#        With this behavior we can have the simplest usage of honest: `$ honest github:user/proj pip:proj`.

set -E
# -------- Commonly used variables -------
HONEST_VERSION="0.0.0"
SCRIPT_DIR="$(readlink -f "$(dirname "$0")")"
HONEST_ROOT="$SCRIPT_DIR"/..
HONEST_SHARE="$HONEST_ROOT"/share/honest
export PATH="$HONEST_ROOT/libexec:$PATH"

# currently supported package vendors
VENDORS=("gem")

HONEST_TMP_DIRS=()

# Color codes
if [[ -t 1 ]]; then
  RED='\033[0;31m'
  GREEN='\033[0;32m'
  YELLOW='\033[0;33m'
  NC='\033[0m' # No Color
fi

# -------- Basic functions --------
version() {
  echo "Honest version $HONEST_VERSION"
}

usage() {
  version
  sed -ne '/^#/!q;s/.\{1,2\}//;1,2d;p' < "$0"
}

die() {
  echo -e "[${RED}ERROR${NC}] $1"
  exit 1
}

info() {
  echo -e "[${GREEN}INFO${NC}] $1"
}

clear_tmp_dirs() {
  rm -fr "${HONEST_TMP_DIRS[@]}"
}

push_tmp() {
  HONEST_TMP_DIRS+=("$1")
}

#######################################
# Check the if the element is in the array.
# Globals:
#   None
# Arguments:
#   <Element>
#   <Array> : e.g. "${array[@]}"
# Returns:
#   succeed:0 / failed:1
#######################################
in_array() {
  local e match="$1"
  shift
  for e; do [[ "$e" == "$match" ]] && return 0; done
  return 1
}

#######################################
# Download the git repo of a git package.
# Globals:
#   None
# Arguments:
#   <Package> The package name with format '<vendor>:<author>/<project>[@..]'
# Returns:
#   None
#   Set global variable 'REPO_PATH'
#######################################
fetch_repo() {
  if [[ -d "$1" ]]; then
    REPO_PATH="$1"
    info "Use local repo directory '$1'"
  else
    REPO_PATH="$(honest-clone "$1")"
    [[ $? != 0 ]] && die "Fail on fetching repo '$1'"
    push_tmp "$REPO_PATH"
  fi
}

#######################################
# Interface function for downloading packages from any vendors.
# This function also sets $vendor and $pkg variable for later use.
# Globals:
#   None
# Arguments:
#   <Package> The package name with format '<vendor>:<package name>'
#   [Package version] Optional package version specified by user
# Returns:
#   None
#######################################
download_package() {
  local cmd=()
  # Match the first : and extract vendor/pkg name
  vendor=${1%%:*}
  pkg=${1#*:}

  # Check format
  [[ "$1" != *":"* ]] && die "Vendor format error - missing separater ':'"
  ( [[ "$vendor" == "" ]] || [[ "$pkg" == "" ]] ) && die "Vendor format error"
  # Check supported vendors
  ! in_array "$vendor" "${VENDORS[@]}" && die "Vendor '$vendor' is currently not supported"

  # Compile the command
  cmd+=(honest-$vendor)
  cmd+=(download $pkg)
  [[ "$2" != "" ]] && cmd+=(-v $2)
  PACKAGE_PATH="$(${cmd[@]})"
  [[ $? != 0 ]] && die "Fail on running '${cmd[@]}'"
  push_tmp "$PACKAGE_PATH"
}

vendor_diff() {
  if [[ "$vendor" == 'gem' ]]; then
    # we have used gem.. so ruby must be installed
    /usr/bin/env ruby "$HONEST_SHARE"/gem/diff.rb $@
  else
    exit 1
  fi
  if [[ $? -eq 0 ]]; then
    info "OK, ${YELLOW}$pkg${NC} is ${GREEN}Honest${NC}!"
    clear_tmp_dirs
  else
    if [[ -t 1 ]]; then
      (set -x; git diff --no-index --diff-filter=M "$REPO_PATH" "$PACKAGE_PATH"data)
    fi
    info "NO, ${YELLOW}$pkg${NC} is ${RED}Unhonest${NC}!"
  fi
}

main() {
  local package_ver=""
  local args=()

  # Parse arguments
  while [[ "$1" != "" ]]; do
    case "$1" in
      -h|--help )
        usage
        exit 0
        ;;
      -V|--version)
        version
        exit 0
        ;;
      -v)
        package_ver="$2"
        shift 2
        ;;
      * )
        # Exit on argument starting with hyphen "-"
        [[ "$1" == "-"* ]] && die "Unknown argument $1"
        # Remember the string type arguments in the array
        args+=("$1")
        shift
        ;;
    esac
  done

  # Check # of input arguments after parsing the input arguments
  [[ ${#args[@]} == 0 ]] && usage && exit 1
  [[ ${#args[@]} < 2 ]] && die "Both <git-url> and <package> are required!"

  fetch_repo "${args[0]}"
  download_package "${args[1]}" $package_ver
  vendor_diff "$REPO_PATH" "$PACKAGE_PATH"
}

main "$@"
