#!/usr/bin/env bash
#
# Usage: honest-gem <command> [arguments...]
#        honest-gem download one_gadget -v 1.4.1
#

SCRIPT_DIR="$(readlink -f "$(dirname "$0")")"
# Import common functions and variables of honest
source "$SCRIPT_DIR"/../share/honest/honest-common.sh

extract() {
  set -e

  tar -xf "$1"
  # TODO: check contains exactly three files
  gunzip metadata.gz

  mkdir -p data
  tar -xzf data.tar.gz -C data

  set +e
}

download() {
  local tmp_dir=$(get_tmp_dir honest-XXXXXXXXXX)

  # Create directory if not exist
  mkdir -p "$tmp_dir"
  # Return the directory name to the caller
  echo "$tmp_dir"

  # Download package in the temp directory
  local mesg="$(cd $tmp_dir && gem fetch --quiet $@ 2>&1)"
  [[ "$mesg" != "Downloaded "* ]] && die "$mesg"

  # Convert the string to <package name>.gem
  local name=$(remove_prefix "$mesg" "Downloaded ")".gem"

  # Go to temp directory and extract the file
  (cd "$tmp_dir" && extract "$name")
}

! command_exist "gem" && die "Command 'gem' is not installed on your system"
[[ "$1" != "download" ]] && exit 1

shift
download $@
