#!/usr/bin/env bash
#
# Usage: honest-clone <git-url> [--quiet]
#
# Options:
#        --quiet
#               Hide the all the output messages except for the name of temp directory
#
# Git Url Parameter:
#        <git-url> can be:
#               - https://<git org>/<author>/<project>[@<branch|commit|tag>]
#               - <github|bitbucket|gitlab>:<author>/<project>[@<branch|commit|tag>]

# Compatibility to MAC
[[ "$OSTYPE" == "darwin"* ]] && readlink() { echo $(cd $(dirname "$2") && pwd)/$(basename "$2"); }

SCRIPT_DIR="$(readlink -f "$(dirname "$0")")"
QUITE_MODE="0"
# Import common functions and variables of honest
source "$SCRIPT_DIR"/../share/honest/honest-common.sh

#######################################
# Convert <vendor>:<author>/<project>[@..] to https://<vendor's url>/<author>/<project>[@..]
# When failed to convert the format, the original string will be return.
# Globals:
#   None
# Arguments:
#   <Repo> The repo name with format '<vendor>:<author>/<project>[@..]'
# Returns:
#   None
#   Echos the transformed string
#######################################
abbr_form() {
  local vendor=${1%%:*}
  local repo=${1#*:}
  local index=$(get_index "$vendor" "${REPO_VENDORS[@]}")

  if [[ "$1" == "https://"* ]]; then
    # Return the original string if it's already in the format
    echo "$1"
  elif [[ "$index" != "-1" ]]; then
    # Return the URL if found
    echo "https://${REPO_VENDORS_HOST[$index]}/$repo"
  else
    # Return the original string if fail to parse
    echo "$1"
  fi
  return 0
}

#######################################
# Parse the tag string from git URL string which can be
# 'https://<author>@github.com/<authors>/<repo>@v1.00'.
# The tag string will be 'v1.00' in this case.
# Globals:
#   None
# Arguments:
#   <Repo> The repo name with format '<vendor>:<author>/<project>[@..]'
# Returns:
#   None
#   Echos the tag string; empty if not found
#######################################
get_tag_from_url() {
  local url=${1#*//} # Remove string before //
  local proj_path=${url#*/} # Remove string before the first /
  local tag=$([[ "$proj_path" == *"@"* ]] && echo ${proj_path##*@} || echo "")

  echo $tag
}

git_clone() {
  local url="$1"
  local tag="$2"
  local path="$3"
  [[ "$QUITE_MODE" == "1" ]] && local extra_git_args="--quiet"
  set -e
  # TODO Use shallow clone or other techniques to improve the speed
  git clone $extra_git_args "$url" "$path"
  cd $path
  # if $tag is not present, checkout to the latest release.
  tag="${tag:-$(git describe --tags `git rev-list --tags --max-count=1 2>/dev/null` 2>/dev/null)}"
  [[ "$tag" != "" ]] && git checkout $extra_git_args --detach "$tag"
  set +e
}

main() {
  local args=()

  # Parse arguments
  while [[ "$1" != "" ]]; do
    case "$1" in
      -h|--help )
        usage
        exit 0
        ;;
      -V|--version)
        version
        exit 0
        ;;
      --quite)
        QUITE_MODE="1"
        shift
        ;;
      * )
        # Exit on argument starting with hyphen "-"
        [[ "$1" == "-"* ]] && die "Unknown argument $1"
        # Remember the string type arguments in the array
        args+=("$1")
        shift
        ;;
    esac
  done

  [[ ${#args[@]} == 0 ]] && usage && exit 0
  local repo="${args[0]}"

  # Verify the input arguments
  check_repo_format "$repo"

  # Convert the format
  local url=$(abbr_form "$repo")

  # Retrieve the tag string from url
  local tag=$(get_tag_from_url $url)

  # Split the string into two parts, repo and tag iff the tag exists in url.
  [[ "$tag" != "" ]] && url=${url%@*}

  local path=$(get_tmp_dir honest-XXXXXXXXXX)
  git_clone "$url" "$tag" "$path"

  # Return the path to caller
  echo "$path"
}

main "$@"
