#!/usr/bin/env bash
#
# Usage: honest-gem gem:<package> <destination> [-v <version>]
#        honest-gem gem:one_gadget /tmp/gem -v 1.4.1

# Compatibility to macOS
[[ "$OSTYPE" == "darwin"* ]] && readlink() { echo $(cd $(dirname "$2") && pwd)/$(basename "$2"); }

SCRIPT_DIR="$(readlink -f "$(dirname "$0")")"
# Import common functions and variables of honest
source "$SCRIPT_DIR"/../share/honest/common.sh

extract() {
  set -e

  tar -xf "$1"
  # TODO: check contains exactly three files
  gunzip metadata.gz

  mkdir -p data
  tar -xzf data.tar.gz -C data

  set +e
}

main() {
  command_or_die 'gem'

  vendor_option_parser "$@"
  # Download package in the temp directory
  local mesg="$(cd "$path" && gem fetch "$package" -v "$package_ver" 2>&1)"
  [[ "$mesg" != "Downloaded "* ]] && die "$mesg"

  # Convert the string to <package name>.gem
  local name=$(remove_prefix "$mesg" "Downloaded ")".gem"

  # Go to temp directory and extract the file
  (cd "$path" && extract "$name")
}

main "$@"
